version: '3.8'

services:
  nexon-webapp:
    image: emidio78/nexon-webapp
    ports:
      - "8080:80"  # Mappa la porta 80 del container alla porta 8080 dell'host
    restart: always  # Riavvia il servizio in caso di errore
    environment:
      - NODE_ENV=production  # Puoi aggiungere variabili d'ambiente se necessarie
  nexon-api:
    image: emidio78/nexon-api
    ports:
      - "8081:80"  # Mappa la porta 80 del container alla porta 8081 dell'host
    restart: always  # Riavvia il servizio in caso di errore

